# don't build tags, it's redundant
if: tag IS blank

language: java
jdk: openjdk8
sudo: false
install: mvn dependency:resolve

cache:
  directories:
    - "$HOME/.m2"

script:
  - mvn clean
  - mvn -Pversion release-candidate:updateVersion -Drevision=`git rev-parse --short HEAD`
  - mvn verify

# https://www.diversit.eu/post/2019/01/05/Github-TravisCi-Bintry-Maven-Setup.html
deploy:
  provider: bintray
  skip_cleanup: true
  file: target/bintray.json
  user: jan-molak
  key: $BINTRAY_API_KEY
  on:
    repo: smartcodeltd/release-candidate-maven-plugin
    branch: master

