# don't build tags, it's redundant
if: tag IS blank

language: java
jdk: openjdk8
sudo: false


cache:
  directories:
    - "$HOME/.m2"

jobs:
  include:
    - stage: test
      script:
        - mvn clean install
        - mvn site
    - stage: version
      if: branch = master
      script: mvn com.smartcodeltd:release-candidate:updateVersion -Drevision=`git rev-parse --short HEAD`

#deploy:
#  provider: bintray
#  dry_run: true
#  edge: true
#  on: master
