# don't build tags, it's redundant
if: tag IS blank

language: java
jdk: openjdk8
sudo: false
install: mvn dependency:resolve

cache:
  directories:
    - "$HOME/.m2"

script:
  - mvn clean verify
  - mvn -Pversion release-candidate:updateVersion -Drevision=`git rev-parse --short HEAD`
  - mvn site
  - VERSION=`mvn -Pversion release-candidate:updateVersion`
  - echo "NEW VERSION" $VERSION
