# don't build tags, it's redundant
if: tag IS blank

language: java
jdk: openjdk8
sudo: false


cache:
  directories:
    - "$HOME/.m2"

jobs:
  include:
    - stage: test
      script:
        - mvn com.smartcodeltd:release-candidate-maven-plugin:updateVersion -Drevision=`git rev-parse --short HEAD`
        - mvn clean verify
        - mvn site

#deploy:
#  provider: bintray
#  dry_run: true
#  edge: true
#  on: master
