# don't build tags, it's redundant
if: tag IS blank

language: java
jdk: openjdk8
sudo: false


cache:
  directories:
    - "$HOME/.m2"

jobs:
  include:
    - stage: test
      script: mvn clean install
    - stage: version
      script: mvn com.smartcodeltd:release-candidate-maven-plugin:updateVersion
    - stage: site
      if: branch = master
      script: mvn site

devploy:
  provider: bintray
  dry_run: true
  on: master
