# don't build tags, it's redundant
if: tag IS blank

language: java
jdk: openjdk8
sudo: false


cache:
  directories:
    - "$HOME/.m2"

jobs:
  include:
    - stage: test
      script:
        - mvn clean verify
        - mvn -Pversion release-candidate:updateVersion -Drevision=`git rev-parse --short HEAD`
        - mvn site
        - VERSION=`mvn -Pversion release-candidate:updateVersion`
    - stage: release
        - echo $VERSION
