# don't build tags, it's redundant
if: tag IS blank

language: java
jdk: openjdk8
sudo: false
install: mvn dependency:resolve

cache:
  directories:
    - "$HOME/.m2"

script:
  - mvn clean
  - mvn -Pversion release-candidate:updateVersion -Drevision=`git rev-parse --short HEAD`
  - mvn verify
  - mvn -Pversion release-candidate:version -DoutputUri="file://\${project.basedir}/target/project.version"
  - VERSION=`cat ./target/project.version`
  - mvn site
  - echo "[VERSION]" $VERSION
