# don't build tags, it's redundant
if: tag IS blank

language: java
jdk: openjdk8
sudo: false
install: mvn dependency:resolve

cache:
  directories:
    - "$HOME/.m2"

script:
  - cp settings.xml $HOME/.m2/settings.xml
  - mvn clean
  - mvn -Pversion release-candidate:updateVersion -Drevision=`git rev-parse --short HEAD`
  - mvn verify site
  - if [ "$TRAVIS_BRANCH" = "master" ]; then mvn -Ppublish -e deploy; fi

